POST http://localhost:8080/api/v1/auth/register?role=STAFF
Content-Type: application/json

{
    "name": "goncalo",
    "email": "goncalo@email.com",
    "password": "top-secret"
}

###

POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "email": "goncalo@email.com",
    "password": "top-secret"
}

###
GET http://localhost:8080/api/v1/bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX1NUQUZGIl0sInN1YiI6ImdvbmNhbG9AZW1haWwuY29tIiwiaWF0IjoxNzYyMDIwMzkxLCJleHAiOjE3NjIxMDY3OTF9.m3XM1asg4irwIBqc__6GnT4Pp80hn0m245_odiquWxo
