POST http://localhost:8080/api/v1/auth/register?role=CITIZEN
Content-Type: application/json

{
    "name": "goncalo",
    "email": "goncalo@email.com",
    "password": "top-secret"
}

###

POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "email": "goncalo@email.com",
    "password": "top-secret"
}

###
GET http://localhost:8080/api/v1/bookings/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX0NJVElaRU4iXSwic3ViIjoiZ29uY2Fsb0BlbWFpbC5jb20iLCJpYXQiOjE3NjIwODQ3MjgsImV4cCI6MTc2MjE3MTEyOH0.vkHQoP83yrJkoasdqoQCRLIYRRNAUOPchkp_OQTpWWw
